name: ClearLagAPI
version: '1.0.0'
main: com.woxloi.clearlagapi.ClearLagAPI
api-version: '1.20'
authors: [ woxloi ]
depend:
  - ClearLag

commands:
  cla:
    description: ClearLagAPI メインコマンド
    usage: /cla <items|help|admin>
    permission: clearlagapi.use
    aliases: [ clearlagapi ]

permissions:
  clearlagapi.use:
    description: /cla コマンドを使用できる
    default: true
  clearlagapi.op:
    description: /cla op コマンドを使用できる（OP自動付与）
    default: op
